package com.fitness.aiservice.controller;

import com.fitness.aiservice.model.Recommendation;
import com.fitness.aiservice.service.RecommendationService;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;

@RestController

@RequiredArgsConstructor // means that if we create an object below then uska constructor 
// automatically generate by Lombok

@RequestMapping("/api/recommendations")
public class RecommendationController {
    private final RecommendationService recommendationService;

    //For a user there will be a lot of activities and if we want to fetch recommendations for all 
    // activities then use this endpt , since fetching all so return type is list ie List<Recommendation>  
    @GetMapping("/user/{userId}")
    public ResponseEntity<List<Recommendation>> getUserRecommendation(@PathVariable String userId) {
        return ResponseEntity.ok(recommendationService.getUserRecommendation(userId));
    }


    //For each activity that user does a recommendation will be generated by Ai service and if we want to
    // fetch that recommendatn then this endpt use
    @GetMapping("/activity/{activityId}")
    public ResponseEntity<Recommendation> getActivityRecommendation(@PathVariable String activityId) {
        return ResponseEntity.ok(recommendationService.getActivityRecommendation(activityId));
    }
}
